<a href="https://colab.research.google.com/github/drskprabhakar/AI-ML-DL-colab-notebooks-coding-models/blob/main/Aishwarya_sia_work_up_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('/content/aishwarya preopkhkvax.xlsx')

In [4]:
df

     pre-op KH  pre-op KV  pre-op Axis  post-op KH  post-op KV  post-op Axis
0        43.50      44.00           90       43.25       44.75            10
1        44.25      44.50           45       41.25       44.50            70
2        47.75      49.50            5       46.00       47.75            35
3        43.75      44.75          165       42.75       45.00           150
4        44.25      44.75           85       44.50       45.50            40
..         ...        ...          ...         ...         ...           ...
102      43.00      43.50          100       43.00       43.75           170
103      45.75      46.25           30       45.75       47.00             5
104      45.25      46.00          135       44.25       45.50           155
105      46.00      46.50           40       46.25       48.00             5
106      42.25      42.75          110       42.00       42.25            65

[107 rows x 6 columns]

In [5]:
df.shape, df.columns

((107, 6),
 Index(['pre-op KH', 'pre-op KV', 'pre-op Axis', 'post-op KH', 'post-op KV',
        'post-op Axis'],
       dtype='object'))

In [8]:
#m1 = pre-op KV - pre-op KV
df['m1'] = df['pre-op KV']-df['pre-op KH']
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,m1
0,43.50,44.00,90,43.25,44.75,10,0.50
1,44.25,44.50,45,41.25,44.50,70,0.25
2,47.75,49.50,5,46.00,47.75,35,1.75
3,43.75,44.75,165,42.75,45.00,150,1.00
4,44.25,44.75,85,44.50,45.50,40,0.50
...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50
103,45.75,46.25,30,45.75,47.00,5,0.50
104,45.25,46.00,135,44.25,45.50,155,0.75
105,46.00,46.50,40,46.25,48.00,5,0.50
106,42.25,42.75,110,42.00,42.25,65,0.50

In [9]:
#m1 = pre-op KV - pre-op KV
df['m2'] = df['post-op KV']-df['post-op KH']
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,m1,m2
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00
...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25

In [21]:
df['a1'] = df['pre-op Axis']
df['a2']= df['post-op Axis']
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,m1,m2,a1,a2
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,90,10
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,45,70
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,5,35
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,165,150
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,85,40
...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,100,170
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,30,5
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,135,155
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,40,5
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,110,65

In [25]:
df['x1'] = df['m1']*np.cos(df['a1']*2)
df['y1'] = df['m1']*np.sin(df['a1']*2)
df['x2'] = df['m2']*np.cos(df['a2']*2)
df['y2'] = df['m2']*np.sin(df['a2']*2)
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,m1,m2,a1,a2,x1,y1,x2,y2
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,90,10,-0.299230,-0.400576,0.612123,1.369418
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,45,70,-0.112018,0.223499,-0.642894,3.185779
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,5,35,-1.468375,-0.952037,1.108309,1.354309
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,165,150,-0.991199,-0.132382,-0.049717,-2.249451
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,85,40,0.468997,0.173325,-0.110387,-0.993889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,100,170,0.243594,-0.436649,0.569751,0.487733
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,30,5,-0.476206,-0.152405,-1.048839,-0.680026
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,135,155,0.738286,-0.132034,-0.656685,1.063610
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,40,5,-0.055194,-0.496944,-1.468375,-0.952037
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,110,65,0.498043,0.044199,-0.091823,-0.232526

In [26]:
df['Xsia']=df['x2']-df['x1']
df['Ysia']=df['y2']-df['y1']
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,m1,m2,a1,a2,x1,y1,x2,y2,Xsia,Ysia
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,90,10,-0.299230,-0.400576,0.612123,1.369418,0.911353,1.769994
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,45,70,-0.112018,0.223499,-0.642894,3.185779,-0.530876,2.962280
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,5,35,-1.468375,-0.952037,1.108309,1.354309,2.576684,2.306346
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,165,150,-0.991199,-0.132382,-0.049717,-2.249451,0.941481,-2.117069
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,85,40,0.468997,0.173325,-0.110387,-0.993889,-0.579385,-1.167213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,100,170,0.243594,-0.436649,0.569751,0.487733,0.326157,0.924382
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,30,5,-0.476206,-0.152405,-1.048839,-0.680026,-0.572633,-0.527621
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,135,155,0.738286,-0.132034,-0.656685,1.063610,-1.394971,1.195644
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,40,5,-0.055194,-0.496944,-1.468375,-0.952037,-1.413182,-0.455093
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,110,65,0.498043,0.044199,-0.091823,-0.232526,-0.589865,-0.276726